/*
 * Created on 2022-12-08 ( Time 13:18:11 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
import { describe, expect, test, beforeEach, jest } from '@jest/globals';
import { Container } from 'inversify';
import 'reflect-metadata';
import { IPersonInfoController } from '../../src/controllers/interfaces/person-info-controller.interface';
import { PersonInfoController } from '../../src/controllers/person-info.controller';
import { IPersonInfoService } from '../../src/services/interfaces/person-info-service.interface';
import { PersonInfoRouter } from '../../src/routes/person-info.router';
import { Symbols } from '../../src/utils/types';
import { PersonInfoService } from '../../src/services/person-info.service';

describe('Test PersonInfo Router', () => {

    let container: Container;
    let router: PersonInfoRouter;
    beforeEach(() => {
        container = new Container();
        container.bind<IPersonInfoService>(Symbols.IPersonInfoService).to(PersonInfoService);
        container.bind<IPersonInfoController>(Symbols.IPersonInfoController).to(PersonInfoController);
        container.bind<PersonInfoRouter>(PersonInfoRouter).to(PersonInfoRouter);
		
		router = container.resolve(PersonInfoRouter);
    });

    test('Routes should initialize successfully', () => {
        expect(router.router.stack.length > 0).toBeTruthy();
    });

    
});

